"""fix

Revision ID: 2fa9278af86f
Revises: 05849b7e0848
Create Date: 2024-02-25 02:29:22.799460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fa9278af86f'
down_revision: Union[str, None] = '05849b7e0848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('user_profiles', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.drop_column('user_profiles', 'last_update_time')
    op.drop_column('user_profiles', 'creation_time')
    op.add_column('users', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'last_update_time')
    op.drop_column('users', 'creation_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('creation_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'update_at')
    op.drop_column('users', 'create_at')
    op.add_column('user_profiles', sa.Column('creation_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('last_update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'update_at')
    op.drop_column('user_profiles', 'create_at')
    # ### end Alembic commands ###
