"""fix bugs

Revision ID: 87e2fefebd6b
Revises: 51629235b806
Create Date: 2024-02-25 20:46:46.491359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '87e2fefebd6b'
down_revision: Union[str, None] = '51629235b806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_params',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('params_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params_value', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('params_name')
    )
    op.create_index(op.f('ix_system_params_id'), 'system_params', ['id'], unique=True)
    op.add_column('user_profiles', sa.Column('custom_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'custom_status')
    op.drop_index(op.f('ix_system_params_id'), table_name='system_params')
    op.drop_table('system_params')
    # ### end Alembic commands ###
